{% set name = "ncdata" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bda53adc0f76a805038300ac4f8cac0a4cb2745c2c1d1d7248c3707e4b482a3b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.7
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools-scm >=7
  run:
    - python >={{ python_min }}
    - numpy
    - dask
    - netCDF4

test:
  requires:
    - python {{ python_min }}
  imports:
    - ncdata

about:
  home: https://github.com/pp-mo/ncdata
  summary: Abstract NetCDF data objects, providing fast data transfer between analysis packages.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://ncdata.readthedocs.io
  dev_url: https://github.com/pp-mo/ncdata"

extra:
  recipe-maintainers:
    - pp-mo
